name: tblog-vue Dockerfile Compile
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm run build
    - name: Login To Docker #登录到镜像仓库
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_IMAGESTORE_USERNAME }}
        password: ${{ secrets.DOCKER_IMAGESTORE_PASSWORD }}
    - name: Build Docker Image # Build Docker镜像并推送到镜像仓库
      uses: docker/build-push-action@v3.0.0
      with:
        tags: falseendless/tblogvue:latest
        file: TBlog.Api/Dockerfile # 指定Dockerfile
        push: true
    - name: Docker Images Lst # 列出所有镜像
      run: docker images
